### ISSUE TITLE
short hand path cause error

### ISSUE THREAD

**Issue by RosApr** [mammadataei/cypress-vite#17]
![f03ec9280b244cfd9f5e21c136c4c4f](https://user-images.githubusercontent.com/11921597/204697536-c71f2239-371b-4e4c-8c16-dc76c79f82d2.png)
![b62429c26c55fcb78faddfb52089a44](https://user-images.githubusercontent.com/11921597/204697549-718f43bf-9780-4410-922f-dd5594d74a95.png)
![2329269e1735a0e7b8ac93e6c2ba46f](https://user-images.githubusercontent.com/11921597/204697550-a2827258-2383-4e0e-bfab-e7f7ddf2b90b.png)
![12f550b640ea07d97f79bbff3bb2cd1](https://user-images.githubusercontent.com/11921597/204697559-97139e82-4b4f-41e7-ad0f-5359e853d2fa.png)

hi~ I`m newer to front end test
my problem is set cypress fold in my project directly like
project
  - src
      - api
          - campaign.ts
  - test
       -e2e
          -  campaign.cy.ts

what i want is reuse variebles in test files but variebles file internal import other file use path alias , this cause error test file cannot read import variebles but if import file internal import other file with no path alias is ok
code like pictures head~
thx~

**Comment by mammadataei** [comment]
Hi @RosApr, I think the issue is coming from your configurations. Can you give me more context (tsconfig, error message, etc.) or create a minimal reproduction so that I can debug it?!

**Comment by MetRonnie** [comment]
I have a project structure like this
```
src/
|-- components/
|   `-- ...
|-- utils/
|   `-- font-size.js
|-- App.vue
`-- main.js
tests/
`-- e2e/
    `-- specs/
        `-- userprofile.cy.js
cypress.config.js
package.json
vite.config.js
```

```js
// vite.config.js
export default defineConfig({
  base: '',
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      ...
    }
  },
  plugins: [
    vue(),
    vuetify()
  ],
...
```

```js
// cypress.config.js
const { defineConfig } = require('cypress')
const vitePreprocessor = require('cypress-vite')
const path = require('path')

module.exports = defineConfig({
  e2e: {
    setupNodeEvents (on, config) {
      on(
        'file:preprocessor',
        vitePreprocessor(path.resolve(__dirname, './vite.config.js'))
      )
      return Object.assign({}, config, {
        specPattern: 'tests/e2e/specs'
      })
    },
    specPattern: 'tests/e2e/specs/**/*.cy.{js,jsx,ts,tsx}'
  },
...
```

This module and its spec
```js
// src/utils/font-size.js
export function getCurrentFontSize () {
  ...
}
```
```js
// tests/e2e/specs/userprofile.cy.js
import { getCurrentFontSize } from '@/utils/font-size'
...
```

Result from `cypress open`

> The following error originated from your test code, not from Cypress.
>  > Cannot find module '@/utils/font-size'

```
    at webpackMissingModule (webpack:///./tests/e2e/specs/userprofile.cy.js:18:0)
    at ./tests/e2e/specs/userprofile.cy.js (webpack:///./tests/e2e/specs/userprofile.cy.js:18:0)
    at __webpack_require__ (webpack:///webpack/bootstrap:19:0)
    at 0 (http://localhost:38886/__cypress/tests?p=tests/e2e/specs/userprofile.cy.js:206:18)
    at __webpack_require__ (webpack:///webpack/bootstrap:19:0)
    at eval (webpack:///webpack/bootstrap:83:0)
    at eval (http://localhost:38886/__cypress/tests?p=tests/e2e/specs/userprofile.cy.js:87:10)
    at eval (<anonymous>)
From previous event:
    at evalScripts (http://localhost:38886/__cypress/runner/cypress_runner.js:158706:58)
    at <unknown> (http://localhost:38886/__cypress/runner/cypress_runner.js:158715:152)
From previous event:
    at runScriptsFromUrls (http://localhost:38886/__cypress/runner/cypress_runner.js:158715:136)
    at Object.runScripts (http://localhost:38886/__cypress/runner/cypress_runner.js:158729:12)
    at $Cypress.onSpecWindow (http://localhost:38886/__cypress/runner/cypress_runner.js:147444:75)
```
