### ISSUE TITLE
u2 is null

### ISSUE THREAD

**Issue by christianitis** [mammadataei/cypress-vite#39]
I have a Laravel project, and I'm attempting to run a simple E2E test. I'm using all default configurations. Component tests work fine, but all E2E tests give me the same error:

> The following error originated from your test code, not from Cypress. It was caused by an unhandled promise rejection.
> u2 is null
>When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
>Cypress could not associate this error to any specific test.
>We dynamically generated a new test to display this failure.

Stack trace:
`at U (http://localhost:40881/__cypress/tests?p=cypress/e2e/login.cy.ts:9505:82)
at <unknown> (http://localhost:40881/__cypress/tests?p=cypress/e2e/login.cy.ts:36882:4)
at <unknown> (http://localhost:40881/__cypress/tests?p=cypress/e2e/login.cy.ts:2:66)
at <unknown> (http://localhost:40881/__cypress/tests?p=cypress/e2e/login.cy.ts:3:3)
at ../driver/src/cypress/script_utils.ts/evalScripts (http://localhost:40881/__cypress/runner/cypress_runner.js:158866:23)
at tryCatcher (http://localhost:40881/__cypress/runner/cypress_runner.js:8914:23)
at gotValue (http://localhost:40881/__cypress/runner/cypress_runner.js:8056:18)
at gotAccum (http://localhost:40881/__cypress/runner/cypress_runner.js:8045:25)
at tryCatcher (http://localhost:40881/__cypress/runner/cypress_runner.js:8914:23)
at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromiseFromHandler (http://localhost:40881/__cypress/runner/cypress_runner.js:6849:31)
at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromise (http://localhost:40881/__cypress/runner/cypress_runner.js:6906:18)
at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromise0 (http://localhost:40881/__cypress/runner/cypress_runner.js:6951:10)
at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromises (http://localhost:40881/__cypress/runner/cypress_runner.js:7031:18)
at _drainQueueStep (http://localhost:40881/__cypress/runner/cypress_runner.js:3621:12)
at _drainQueue (http://localhost:40881/__cypress/runner/cypress_runner.js:3614:24)
at ../../node_modules/bluebird/js/release/async.js/</Async.prototype._drainQueues (http://localhost:40881/__cypress/runner/cypress_runner.js:3630:16)
at ../../node_modules/bluebird/js/release/async.js/</Async/this.drainQueues (http://localhost:40881/__cypress/runner/cypress_runner.js:3500:14)
`

Let me know if you need anything else.

**Comment by mammadataei** [comment]
@christianitis, Thanks for reporting. Can you provide more information about the error? Try to run in debug mode to see if there is any error in the compilation. A reproduction might help to debug.

**Comment by christianitis** [comment]
> @christianitis, Thanks for reporting. Can you provide more information about the error? Try to run in debug mode to see if there is any error in the compilation. A reproduction might help to debug.

Running `cypress open -e DEBUG=cypress-vite` doesn't seem to give me any extra info (maybe I'm not using the config options correctly). Compiles fine, the errors seem to be at runtime.
It should be noted that the error messages I copied in the original issue were from when I ran the tests in Firefox. When I run the same tests in Chromium or Electron, I get:

>The following error originated from your test code, not from Cypress. It was caused by an unhandled promise rejection.
>Cannot read properties of null (reading 'dataset')
>When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
>Cypress could not associate this error to any specific test.
>We dynamically generated a new test to display this failure.

Stack trace:
```
at U (http://localhost:44707/__cypress/tests?p=cypress/e2e/login.cy.ts:40238:106)
at eval (http://localhost:44707/__cypress/tests?p=cypress/e2e/login.cy.ts:46023:3)
at eval (http://localhost:44707/__cypress/tests?p=cypress/e2e/login.cy.ts:2:66)
at eval (http://localhost:44707/__cypress/tests?p=cypress/e2e/login.cy.ts:3:3)
at eval (<anonymous>)
```

My cypress.config.ts:

```
import { defineConfig } from "cypress";
import vitePreprocessor from "cypress-vite";
import * as path from "path";

export default defineConfig({
    e2e: {
        setupNodeEvents(on) {
            on("file:preprocessor", vitePreprocessor(path.resolve(__dirname, './vite.config.js')));
        },
    },
});
```
vite.config.js:

```
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import react from '@vitejs/plugin-react';

export default defineConfig({
    plugins: [
        laravel({
            input: ['resources/js/app.jsx'],
            refresh: true,
        }),
        react()
    ],
});
```
 I'm using pretty much as default of a configuration as possible across the board, aside from setting up Typescript with Laravel (but that wasn't a major change).

app.jsx:
```
import './bootstrap';

import { createInertiaApp } from '@inertiajs/react'
import { createRoot } from 'react-dom/client'

createInertiaApp({
    resolve: name => {
        const pages = import.meta.glob(['./Pages/**/*.tsx', "./Pages/**/*.jsx"], { eager: true })
        return pages[`./Pages/${name}.jsx`] ?? pages[`./Pages/${name}.tsx`]
    },
    setup({ el, App, props }) {
        createRoot(el).render(<App {...props} />)
    },
})
```
Note that `createInertiaApp` does return a promise, but even adding a blank `onFinally` handler does nothing.
The page I tested does not make any promises (until the Login button is clicked), although it is meant to be rendered by Inertia. [The Inertia docs](https://inertiajs.com/testing#end-to-end-tests) do mention Cypress.
The test being run (login.cy.ts):
```
describe('template spec', () => {
  it('passes', () => {
    cy.visit('https://example.cypress.io')
  })
})
```
(As you can see, this is just the default spec generated by Cypress. Removing the `cy.visit` directive does nothing.

Please do let me know if you need anything else, I am happy to help.

**Comment by mammadataei** [comment]
@christianitis Thanks for the in-depth explanation. Since the test file runs successfully, I think it's not a compilation error. To get the debug output run `DEBUG=cypress-vite cypress open`. If you could create a reproduction, it would help me debug better.
